/**
 * @fileoverview Sidecar binary integrity verification.
 *
 * The single most important defense against a tampered binary serving the
 * user's traffic. We compute a SHA-256 of the Go binary at build time and
 * compare against it at every process spawn.
 *
 * If an attacker swaps `osm-agent` for a malicious build, the hash will
 * not match and the app refuses to boot. This complements code signing —
 * a Developer ID signature proves the bundle came from us; the hash
 * comparison proves the binary inside hasn't been replaced after install
 * (e.g. by a worm with file-write access in the user's home).
 *
 * Implements (from {@link ../../../osmRouter/05 - Security Spec.md}):
 *   - **S5.1** — build script computes SHA-256 → `sidecar-hash.json`
 *   - **S5.2** — Main recomputes SHA-256 at boot, compares
 *   - **S5.3** — mismatch refuses boot with a fatal modal
 *   - **S5.4** — binary always loaded from `process.resourcesPath`,
 *               never from `PATH` or a user-writable location
 *
 * Time-of-check / time-of-use risk (R11): we hash, then spawn. An attacker
 * with write access could theoretically swap the binary between those two
 * operations. We accept this risk in v0.1 because (a) the macOS app
 * bundle's Resources directory is read-only in the user partition under
 * macOS gatekeeper, and (b) the spawn happens within microseconds of the
 * hash. A future hardening pass could keep an fd open between hash and
 * exec (`fexecve`-style).
 */

import crypto from "node:crypto";
import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";

/**
 * Result of a sidecar integrity check. `ok: true` means the binary on disk
 * matches the hash file shipped with the app.
 */
export interface IntegrityResult {
  /** Did the hashes match? */
  ok: boolean;
  /** The hex hash recorded in `sidecar-hash.json`. */
  expected: string;
  /** The hex hash we just computed (empty string if the file/name was wrong). */
  actual: string;
  binaryPath: string;
  hashFilePath: string;
}

/**
 * On-disk schema for `sidecar-hash.json`. Generated by
 * `scripts/hash-sidecar.mjs` immediately after `go build`.
 */
export interface SidecarHashFile {
  /** Basename of the binary the hash applies to. Used to defend against rename attacks. */
  binary: string;
  /** Algorithm. We only support SHA-256 today. */
  algo: "sha256";
  /** Hex-encoded digest. */
  hash: string;
  /** ISO-8601 timestamp of the build. Informational. */
  builtAt: string;
}

/**
 * Stream-hash a file with SHA-256.
 *
 * Streaming (rather than read-all-then-hash) lets us hash binaries larger
 * than RAM without changing the API. The 6.3 MB Go binary is tiny but the
 * approach scales.
 *
 * @param filePath — absolute path to the file
 * @returns hex-encoded digest (lowercase)
 */
export async function computeSha256(filePath: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash("sha256");
    const stream = fs.createReadStream(filePath);
    stream.on("data", (chunk) => hash.update(chunk));
    stream.on("end", () => resolve(hash.digest("hex")));
    stream.on("error", reject);
  });
}

/**
 * Verify the sidecar binary on disk against its build-time hash.
 *
 * Returns `{ ok: false }` for hash mismatches and basename mismatches.
 * Throws for environmental errors (missing files, unsupported algorithm)
 * so the caller can distinguish "tampered" from "broken install".
 *
 * @throws if the hash file is missing, unreadable, or specifies an
 *   unsupported algorithm.
 */
export async function verifySidecarBinary(opts: {
  binaryPath: string;
  hashFilePath: string;
}): Promise<IntegrityResult> {
  const hashRaw = await fsp.readFile(opts.hashFilePath, "utf8");
  const hashFile = JSON.parse(hashRaw) as SidecarHashFile;
  if (hashFile.algo !== "sha256") {
    throw new Error(`unsupported-hash-algo:${hashFile.algo}`);
  }
  // Basename check: defends against an attacker renaming a malicious binary
  // to a name we accept, then patching `sidecar-hash.json` to point at it.
  if (path.basename(opts.binaryPath) !== hashFile.binary) {
    return {
      ok: false,
      expected: hashFile.hash,
      actual: "",
      binaryPath: opts.binaryPath,
      hashFilePath: opts.hashFilePath,
    };
  }
  const actual = await computeSha256(opts.binaryPath);
  return {
    ok: actual === hashFile.hash,
    expected: hashFile.hash,
    actual,
    binaryPath: opts.binaryPath,
    hashFilePath: opts.hashFilePath,
  };
}

/**
 * Resolve the sidecar binary path inside the packaged .app bundle.
 *
 * In production, `process.resourcesPath` points to the .app's `Contents
 * /Resources/` — read-only territory inside the signed bundle. In dev
 * (`electron-forge start`), `resourcesPath` is set to the Electron.app
 * inside `node_modules`, which doesn't contain our binary, so we fall back
 * to `apps/desktop/resources/`.
 *
 * Naming convention: `osm-agent-<platform>-<arch>[.exe]`. The build script
 * follows the same convention so basenames line up with
 * `sidecar-hash.json`.
 *
 * @param opts.resourcesPath — `process.resourcesPath` value (or undefined in dev)
 * @param opts.devRoot       — repo-relative dev fallback (e.g. apps/desktop)
 * @param opts.platform      — Node's process.platform
 * @param opts.arch          — Node's process.arch
 */
export function resolveSidecarPath(opts: {
  resourcesPath: string | undefined;
  devRoot: string;
  platform: NodeJS.Platform;
  arch: string;
}): { binaryPath: string; hashFilePath: string } {
  const binName = `osm-agent-${opts.platform === "win32" ? "windows" : opts.platform}-${opts.arch}${
    opts.platform === "win32" ? ".exe" : ""
  }`;
  const rp = opts.resourcesPath ?? path.join(opts.devRoot, "resources");
  return {
    binaryPath: path.join(rp, binName),
    hashFilePath: path.join(rp, "sidecar-hash.json"),
  };
}
