#!/usr/bin/env bash
# Mint a complete set of production secrets in .env-format.
#
#   ./scripts/generate-secrets.sh >> .env
#
# Rerunning rotates EVERYTHING and invalidates all sessions.
set -e
command -v openssl >/dev/null || { echo "openssl required" >&2; exit 1; }

hex() { openssl rand -hex 32; }
pw()  { openssl rand -base64 24 | tr -d '/+=' | head -c 32; }

cat <<EOF
# Generated by generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
OSM_JWT_SECRET=$(hex)
OSM_OTP_MASTER_SECRET=$(hex)
OSM_CSRF_SECRET=$(hex)
OSM_AES_MASTER_KEY=$(hex)
OSM_PROXY_NODE_SECRET=$(hex)
POSTGRES_PASSWORD=$(pw)
REDIS_PASSWORD=$(pw)
EOF
