#!/usr/bin/env bash
#
# Generate a complete set of production secrets for osmRouter.
# Prints them to stdout in `.env` format — pipe into your secret manager or
# append to `.env` directly:
#
#   ./scripts/generate-secrets.sh >> .env
#
# Re-running rotates ALL secrets, which would invalidate every active session
# and break proxy-node auth. Do that intentionally.
set -e

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required" >&2
  exit 1
fi

random_hex() { openssl rand -hex 32; }
random_pw()  { openssl rand -base64 24 | tr -d '/+=' | head -c 32; }

cat <<EOF
# Generated by generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Replace the «CHANGE» placeholders in .env with these values.

OSM_JWT_SECRET=$(random_hex)
OSM_OTP_MASTER_SECRET=$(random_hex)
OSM_CSRF_SECRET=$(random_hex)
OSM_AES_MASTER_KEY=$(random_hex)
OSM_PROXY_NODE_SECRET=$(random_hex)
POSTGRES_PASSWORD=$(random_pw)
REDIS_PASSWORD=$(random_pw)
EOF
